package com.example.filmes.model

data class Serie(
    val adult: Boolean,
    val backdrop_path: String,
    val created_by: List<CreatedByX>,
    val episode_run_time: List<Int>,
    val first_air_date: String,
    val genres: List<GenreX>,
    val homepage: String,
    val id: Int,
    val in_production: Boolean,
    val languages: List<String>,
    val last_air_date: String,
    val last_episode_to_air: LastEpisodeToAirX,
    val name: String,
    val networks: List<NetworkX>,
    val next_episode_to_air: NextEpisodeToAir,
    val number_of_episodes: Int,
    val number_of_seasons: Int,
    val origin_country: List<String>,
    val original_language: String,
    val original_name: String,
    val overview: String,
    val popularity: Double,
    val poster_path: String,
    val production_companies: List<ProductionCompany>,
    val production_countries: List<ProductionCountry>,
    val seasons: List<SeasonX>,
    val spoken_languages: List<SpokenLanguageX>,
    val status: String,
    val tagline: String,
    val type: String,
    val vote_average: Double,
    val vote_count: Int
)